myshop/myshop/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # Examples:
    # url(r'^$', 'myshop.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include("shop.urls", namespace='shop')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

myshop/shop/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.product_list, name='product_list'),
    url(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
]

myshop/cart/models.py
from django.db import models

# Create your models here.

myshop/shop/models.py
from django.db import models

# Create your models here.
from django.core.urlresolvers import reverse


class Category(models.Model):
    name = models.CharField(max_length=200,
                            db_index=True)
    slug = models.SlugField(max_length=200,
                            db_index=True,
                            unique=True)
    
    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'
    
    def __str__(self):
        return self.name

    # 解析绝对路径
    def get_absolute_url(self):
        return reverse("shop:product_list_by_category", args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category,
                                 related_name='products')  # 关联别名
    name = models.CharField(max_length=200,
                            db_index=True)
    slug = models.SlugField(max_length=200,
                            db_index=True)
    image = models.ImageField(upload_to="products/%Y/%m/%d",
                              blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10,
                                decimal_places=2)
    stock = models.PositiveIntegerField()  # 库存，正整数
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("shop:product_detail",
                       args=[self.id, self.slug])

myshop/cart/views.py
from django.shortcuts import render

# Create your views here.

myshop/shop/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import get_object_or_404
from .models import Category
from .models import Product


def product_list(request, category_slug=None):
    """
    产品列表
    :param request:
    :param category_slug:
    :return:
    """
    category = None
    categories = Category.objects.all()  # 所有的类目
    products = Product.objects.filter(available=True)  # 只需要可用的产品
    # 判断是否有category slug
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request,
                  "shop/product/list.html",
                  {"category": category,
                   "categories": categories,
                   "products": products})


def product_detail(request, id, slug):
    product = get_object_or_404(Product,
                                available=True,
                                id=id,
                                slug=slug)
    return render(request,
                  "shop/product/detail.html",
                  {"product": product})

myshop/shop/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>{% block title %}My shop{% endblock %}</title>
    <link href="{% static "css/base.css" %}" rel="stylesheet">
</head>
<body>
    <div id="header">
        <a href="/" class="logo">My shop</a>
    </div>
    <div id="subheader">
        <div class="cart">
            {% with total_items=cart|length %}
                {% if cart|length > 0 %}
                    Your cart: 
                    <a href="{% url "cart:cart_detail" %}">
                        {{ total_items }} item{{ total_items|pluralize }}, ${{ cart.get_total_price }}
                    </a>
                {% else %}
                    Your cart is empty.
                {% endif %}
            {% endwith %}
        </div>
    </div>
    <div id="content">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

myshop/shop/templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}
        My shop
    {% endblock %}</title>
    <link href="{% static "css/base.css" %}" rel="stylesheet">
</head>
<body>
    <div id="header">
        <a href="/" class="logo">Talen's shop</a>
    </div>
    <div id="subheader">
        <div class="cart">
            You cart is empty!
        </div>
    </div>
    <div id="content">
        {% block content %}
        
        {% endblock %}
    </div>
</body>
</html>

myshop/shop/templates/shop/product/detail.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
    {{ product.name }}
{% endblock %}

{% block content %}
    <div class="product-detail">
        <img src="{% if product.image %}
                    {{ product.image.url }}
                {% else %}
                    {% static "img/no_image.png" %}
                {% endif %}">
        <h1>{{ product.name }}</h1>
        <h2><a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a></h2>
        <p class="price">${{ product.price }}</p>
        {% comment %}
        <!--<form action="{% url "cart:cart_add" product.id %}" method="post">
            {{ cart_product_form }}
            {% csrf_token %}
            <input type="submit" value="Add to cart">
        </form>-->
        {% endcomment %}
        {{ product.description|linebreaks }}
    </div>
{% endblock %}

        
        
        

myshop/shop/templates/shop/product/list.html
{% extends "shop/base.html" %}
{% load static %}
{% load thumbnail %}

<!--标题-->
{% block title %}
    {% if category %}
        {{ category.name }}
    {% else %}
        Products
    {% endif %}
{% endblock %}

<!--左侧产品类目，右侧主窗口产品列表-->
{% block content %}
    <!--左侧产品类目-->
    <div id="sidebar">
        <h3>Categories</h3>
        <ul>
            <!--判断是否是传递显示指定类目的产品，没有传递默认选中显示全部-->
            <li {% if not category %}
                    class="selected"
            {% endif %}>
                <a href="{% url "shop:product_list"%}">All</a>
            </li>
            <!--迭代显示所有类目（顺便判断一个是否在有传递指定category的情况下默认选中相匹配的category,显示相应的产品。）-->
            {% for cate in categories %}
                <li {% if cate.slug == category.slug %}
                    class="selected"
                {% endif %}>
                    <a href="{{ cate.get_absolute_url }}">{{ cate.name }}</a>
                </li>
            {% endfor %}
        </ul>
    </div>
    <!--右侧主窗口产品列表-->
    <div id="main" class="product-list">
        <h1 {% if category %}
                {{ category.name }}
            {% else %}
                Products
        {% endif %}>
        </h1>
        {% for product in products %}
            <div class="item">
            <!--图-->
            <a href="{{ product.get_absolute_url }}">
                <img src="{% if product.image %}
                    {% thumbnail product.image "300x200" crop="100%" as im %}
                        {{ im.url }}
                    {% endthumbnail %}
                {% else %}
                    {% static "img/no_image.png" %}
                {% endif %}">
            </a>
            <!--名-->
            <a href="{{ product.get_absolute_url }}">
                {{ product.name }}
            </a>
            <!--价-->
            {{ product.price }}
            </div>
        {% endfor %}
    </div>
{% endblock %}